### PR TITLE
Tabulation of messages in each language.

### PR DESCRIPTION
**Pull request by Halo1234**
T/O

### CODE REVIEW

**Comment by a-rabin** [comment]
I get this error: 
Cannot suggest graphics extension for file://...src/goki2/memory_button

**Comment by Halo1234** [comment]
Added memory_button to EnglishVer/EnglishPullReq.
I haven't committed GOKI2MessageTable because I feel like the commits will probably conflict.

Also, please see GError.tjs for the English version of the source.

**Comment by a-rabin** [comment]
I now get this error when running run_en.bat:
image

**Comment by Halo1234** [comment]
sorry. Fixed.

**Comment by a-rabin** [comment]
> I get this error: Cannot suggest graphics extension for file://...src/goki2/memory_button

Now I get the above error again.

**Comment by Halo1234** [comment]
The resource has been registered.

**Comment by a-rabin** [comment]
Thank you. The example runs as intended. But the top of the text is cut off as shown.
image
I should be able to translate the example program lines soon.

**Comment by Halo1234** [comment]
There seem to be some bugs in the English translation.
I'll fix it after merging.

**Comment by Halo1234** [comment]
If I don't get a response within the next week, I'll merge it.

**Comment by a-rabin** [comment]
Right click test still shows Japanese.
image

**Comment by Halo1234** [comment]
Fixed.

**Comment by Halo1234** [comment]
It looks like the upper part of the letters are cut off.
It will not be reproduced here.

**Comment by Halo1234** [comment]
I have added the code for investigation.
Could you please take a screenshot of the console log?

**Comment by a-rabin** [comment]
`18:13:56 ================================================================================
18:13:56 Scenario loaded : ModRightClickTestEn.gs
18:13:56 call modules handler : onConductorScenarioLoaded
18:13:56 ModRightClickTestEn.gs :
18:13:56 call modules handler : onBeforeConductorLabel
18:13:56 onLabelStore(*label, , 0) processed in 2 ms.
18:13:56 call modules handler : onConductorLabel
18:13:56 ModRightClickTestEn.gs :
18:13:56 ModRightClickTestEn.gs : @using_mod_message
18:13:56 ModRightClickTestEn.gs : @log message="Change output destination to ModMessage."
18:13:56 Change output destination to ModMessage.
18:13:56 ModRightClickTestEn.gs :
18:13:56 ModRightClickTestEn.gs : @cr_handling ignore
18:13:56 ModRightClickTestEn.gs :
18:13:56 ModRightClickTestEn.gs : @show_message layer=message0
18:13:56 call modules handler : onShowMessageLayer
18:13:56 ModRightClickTestEn.gs :
18:13:56 call modules handler : onBeforeConductorLabel
18:13:56 onLabelStore(*label:2, , 1) processed in 2 ms.
18:13:56 call modules handler : onConductorLabel
18:13:56 ModRightClickTestEn.gs : @rclick enabled jump storage=ModRightClickTest target=*right_click_1
18:13:56 ModRightClickTestEn.gs : Right click test. [p][cm]
18:13:56 call modules handler : onWindowLeftClick
18:13:56 signal: left_click
18:13:56 ModRightClickTestEn.gs :
18:13:56 call modules handler : onBeforeConductorLabel
18:13:56 onLabelStore(*right_click_1, , 1) processed in 0 ms.
18:13:56 call modules handler : onConductorLabel
18:13:56 ModRightClickTestEn.gs :
18:13:56 call modules handler : onBeforeConductorLabel
18:13:56 onLabelStore(*label:3, , 1) processed in 2 ms.
18:13:56 call modules handler : onConductorLabel
18:13:56 ModRightClickTestEn.gs : @rclick enabled call storage=ModRightClickTest target=*right_click_2
18:13:56 ModRightClickTestEn.gs : This is a test of the right click subroutine. [p][cm]
18:13:58 call modules handler : onWindowRightClick
18:13:58 call modules handler : onConductorScenarioLoad
18:13:58 ================================================================================
18:13:58 Scenario loaded : ModRightClickTest.gs
18:13:58 call modules handler : onConductorScenarioLoaded
18:13:58 ModRightClickTest.gs : call stack depth before calling : 0
18:13:58 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
18:13:58 ModRightClickTest.gs : jumped to : *right_click_2
18:13:58 call modules handler : onBeforeConductorLabel
18:13:58 onLabelStore(*right_click_2, , 0) processed in 0 ms.
18:13:58 call modules handler : onConductorLabel
18:13:58 ModRightClickTest.gs : ここは右クリックサブルーチンの中です。[p]
18:14:03 (info) CPU clock : 3893.2MHz
18:14:15 call modules handler : onWindowLeftClick
18:14:15 signal: left_click
18:14:15 ModRightClickTest.gs : @return
18:14:15 call modules handler : onConductorReturn
18:14:15 ModRightClickTestEn.gs :
18:14:15 ModRightClickTestEn.gs : @jump target=*next
18:14:15 call modules handler : onConductorJump
18:14:15 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
18:14:15 ModRightClickTestEn.gs : jumped to : *next
18:14:15 call modules handler : onBeforeConductorLabel
18:14:15 onLabelStore(*next, , 1) processed in 3 ms.
18:14:15 call modules handler : onConductorLabel
18:14:15 ModRightClickTestEn.gs : Right-click test complete. [p][cm]
18:14:17 call modules handler : onWindowRightClick
18:14:17 call modules handler : onConductorScenarioLoad
18:14:17 ================================================================================
18:14:17 Scenario loaded : ModRightClickTest.gs
18:14:17 call modules handler : onConductorScenarioLoaded
18:14:17 ModRightClickTest.gs : call stack depth before calling : 0
18:14:17 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
18:14:17 ModRightClickTest.gs : jumped to : *right_click_2
18:14:17 call modules handler : onBeforeConductorLabel
18:14:17 onLabelStore(*right_click_2, , 0) processed in 0 ms.
18:14:17 call modules handler : onConductorLabel
18:14:17 ModRightClickTest.gs : ここは右クリックサブルーチンの中です。[p]
18:14:25 call modules handler : onWindowRightClick
18:14:25 call modules handler : onHideMessageLayerByUser
18:14:27 call modules handler : onWindowRightClick
18:14:27 call modules handler : onShowMessageLayerByUser
18:14:27 call modules handler : onWindowLeftClick
18:14:27 signal: left_click
18:14:27 ModRightClickTest.gs : @return
18:14:27 call modules handler : onConductorReturn
18:14:27 ModRightClickTestEn.gs :
18:14:27 ModRightClickTestEn.gs : @rclick !call !jump
18:14:27 ModRightClickTestEn.gs : @hide_message layer=message0
18:14:27 call modules handler : onHideMessageLayer
18:14:27 ModRightClickTestEn.gs : @wait_hide_message
18:14:28 signal: message0_hide_completed
18:14:28 ModRightClickTestEn.gs :
18:14:28 ModRightClickTestEn.gs :
18:14:28 call modules handler : onConductorScenarioLoad`

**Comment by a-rabin** [comment]
> 18:18:17 call modules handler : onConductorScenarioLoad
18:18:17 ================================================================================
18:18:17 Scenario loaded : ModRightClickTestEn.gs
18:18:17 call modules handler : onConductorScenarioLoaded
18:18:17 ModRightClickTestEn.gs :
18:18:17 call modules handler : onBeforeConductorLabel
18:18:17 onLabelStore(*label, , 0) processed in 3 ms.
18:18:17 call modules handler : onConductorLabel
18:18:17 ModRightClickTestEn.gs :
18:18:17 ModRightClickTestEn.gs : @using_mod_message
18:18:17 ModRightClickTestEn.gs : @log message="Change output destination to ModMessage."
18:18:17 Change output destination to ModMessage.
18:18:17 ModRightClickTestEn.gs :
18:18:17 ModRightClickTestEn.gs : @cr_handling ignore
18:18:17 ModRightClickTestEn.gs :
18:18:17 ModRightClickTestEn.gs : @show_message layer=message0
18:18:17 call modules handler : onShowMessageLayer
18:18:17 ModRightClickTestEn.gs :
18:18:17 call modules handler : onBeforeConductorLabel
18:18:17 onLabelStore(*label:2, , 1) processed in 2 ms.
18:18:17 call modules handler : onConductorLabel
18:18:17 ModRightClickTestEn.gs : @rclick enabled jump storage=ModRightClickTestEn target=*right_click_1
18:18:17 ModRightClickTestEn.gs : Right click test. [p][cm]
18:18:17 pos [R]: (0 + 0, 0 + 0)
18:18:17 pos [i]: (0 + 0, 0 + 0)
18:18:17 pos [g]: (0 + 0, 0 + 0)
18:18:17 pos [h]: (0 + 0, 0 + 0)
18:18:17 pos [t]: (0 + 0, 0 + 0)
18:18:17 pos [ ]: (0 + 0, 0 + 0)
18:18:17 pos [c]: (0 + 0, 0 + 0)
18:18:17 pos [l]: (0 + 0, 0 + 0)
18:18:17 pos [i]: (0 + 0, 0 + 0)
18:18:17 pos [c]: (0 + 0, 0 + 0)
18:18:17 pos [k]: (0 + 0, 0 + 0)
18:18:17 pos [ ]: (0 + 0, 0 + 0)
18:18:17 pos [t]: (0 + 0, 0 + 0)
18:18:17 pos [e]: (0 + 0, 0 + 0)
18:18:17 pos [s]: (0 + 0, 0 + 0)
18:18:17 pos [t]: (0 + 0, 0 + 0)
18:18:18 pos [.]: (0 + 0, 0 + 0)
18:18:18 pos [ ]: (0 + 0, 0 + 0)
18:18:18 call modules handler : onWindowLeftClick
18:18:18 signal: left_click
18:18:18 pos [g]: (0 + 0, 0 + 0)
18:18:18 pos [h]: (0 + 0, 0 + 0)
18:18:18 pos [t]: (0 + 0, 0 + 0)
18:18:18 pos [ ]: (0 + 0, 0 + 0)
18:18:18 pos [R]: (0 + 0, 0 + 0)
18:18:18 pos [i]: (0 + 0, 0 + 0)
18:18:18 pos [c]: (0 + 0, 0 + 0)
18:18:18 pos [l]: (0 + 0, 0 + 0)
18:18:18 pos [i]: (0 + 0, 0 + 0)
18:18:18 pos [c]: (0 + 0, 0 + 0)
18:18:18 pos [k]: (0 + 0, 0 + 0)
18:18:18 pos [ ]: (0 + 0, 0 + 0)
18:18:18 pos [t]: (0 + 0, 0 + 0)
18:18:18 pos [e]: (0 + 0, 0 + 0)
18:18:18 pos [s]: (0 + 0, 0 + 0)
18:18:18 pos [ ]: (0 + 0, 0 + 0)
18:18:18 pos [.]: (0 + 0, 0 + 0)
18:18:18 pos [t]: (0 + 0, 0 + 0)
18:18:18 ModRightClickTestEn.gs :
18:18:18 call modules handler : onBeforeConductorLabel
18:18:18 onLabelStore(*right_click_1, , 1) processed in 0 ms.
18:18:18 call modules handler : onConductorLabel
18:18:18 ModRightClickTestEn.gs :
18:18:18 call modules handler : onBeforeConductorLabel
18:18:18 onLabelStore(*label:3, , 1) processed in 2 ms.
18:18:18 call modules handler : onConductorLabel
18:18:18 ModRightClickTestEn.gs : @rclick enabled call storage=ModRightClickTestEn target=*right_click_2
18:18:18 ModRightClickTestEn.gs : This is a test of the right click subroutine. [p][cm]
18:18:18 pos [T]: (0 + 0, 0 + 0)
18:18:18 pos [h]: (0 + 0, 0 + 0)
18:18:18 pos [i]: (0 + 0, 0 + 0)
18:18:18 pos [s]: (0 + 0, 0 + 0)
18:18:18 pos [ ]: (0 + 0, 0 + 0)
18:18:18 pos [i]: (0 + 0, 0 + 0)
18:18:18 pos [s]: (0 + 0, 0 + 0)
18:18:18 pos [ ]: (0 + 0, 0 + 0)
18:18:18 pos [a]: (0 + 0, 0 + 0)
18:18:18 pos [ ]: (0 + 0, 0 + 0)
18:18:18 pos [t]: (0 + 0, 0 + 0)
18:18:18 pos [e]: (0 + 0, 0 + 0)
18:18:18 pos [s]: (0 + 0, 0 + 0)
18:18:18 pos [t]: (0 + 0, 0 + 0)
18:18:18 pos [ ]: (0 + 0, 0 + 0)
18:18:18 pos [o]: (0 + 0, 0 + 0)
18:18:18 pos [f]: (0 + 0, 0 + 0)
18:18:18 pos [ ]: (0 + 0, 0 + 0)
18:18:18 pos [t]: (0 + 0, 0 + 0)
18:18:18 pos [h]: (0 + 0, 0 + 0)
18:18:18 pos [e]: (0 + 0, 0 + 0)
18:18:18 pos [ ]: (0 + 0, 0 + 0)
18:18:18 pos [r]: (0 + 0, 0 + 0)
18:18:18 pos [i]: (0 + 0, 0 + 0)
18:18:18 pos [g]: (0 + 0, 0 + 0)
18:18:19 pos [h]: (0 + 0, 0 + 0)
18:18:19 pos [t]: (0 + 0, 0 + 0)
18:18:19 pos [ ]: (0 + 0, 0 + 0)
18:18:19 pos [c]: (0 + 0, 0 + 0)
18:18:19 pos [l]: (0 + 0, 0 + 0)
18:18:19 pos [i]: (0 + 0, 0 + 0)
18:18:19 pos [c]: (0 + 0, 0 + 0)
18:18:19 pos [k]: (0 + 0, 0 + 0)
18:18:19 pos [ ]: (0 + 0, 0 + 0)
18:18:19 pos [s]: (0 + 0, 0 + 0)
18:18:19 pos [u]: (0 + 0, 0 + 0)
18:18:19 pos [b]: (0 + 0, 0 + 0)
18:18:19 pos [r]: (0 + 0, 0 + 0)
18:18:19 pos [o]: (0 + 0, 0 + 0)
18:18:19 pos [u]: (0 + 0, 0 + 0)
18:18:19 pos [t]: (0 + 0, 0 + 0)
18:18:19 pos [i]: (0 + 0, 0 + 0)
18:18:19 pos [n]: (0 + 0, 0 + 0)
18:18:19 pos [e]: (0 + 0, 0 + 0)
18:18:19 pos [.]: (0 + 0, 0 + 0)
18:18:19 pos [ ]: (0 + 0, 0 + 0)
18:18:20 call modules handler : onWindowRightClick
18:18:20 call modules handler : onConductorScenarioLoaded
18:18:20 ModRightClickTestEn.gs : call stack depth before calling : 0
18:18:20 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
18:18:20 ModRightClickTestEn.gs : jumped to : *right_click_2
18:18:20 call modules handler : onBeforeConductorLabel
18:18:20 onLabelStore(*right_click_2, , 0) processed in 0 ms.
18:18:20 call modules handler : onConductorLabel
18:18:20 ModRightClickTestEn.gs : This is inside the right-click subroutine. [p]
18:18:20 pos [T]: (0 + 0, 0 + 0)
18:18:20 pos [h]: (0 + 0, 0 + 0)
18:18:20 pos [i]: (0 + 0, 0 + 0)
18:18:20 pos [s]: (0 + 0, 0 + 0)
18:18:20 pos [ ]: (0 + 0, 0 + 0)
18:18:20 pos [i]: (0 + 0, 0 + 0)
18:18:20 pos [s]: (0 + 0, 0 + 0)
18:18:20 pos [ ]: (0 + 0, 0 + 0)
18:18:20 pos [i]: (0 + 0, 0 + 0)
18:18:20 pos [n]: (0 + 0, 0 + 0)
18:18:20 pos [s]: (0 + 0, 0 + 0)
18:18:20 pos [i]: (0 + 0, 0 + 0)
18:18:20 pos [d]: (0 + 0, 0 + 0)
18:18:20 pos [e]: (0 + 0, 0 + 0)
18:18:20 pos [ ]: (0 + 0, 0 + 0)
18:18:20 pos [t]: (0 + 0, 0 + 0)
18:18:20 pos [h]: (0 + 0, 0 + 0)
18:18:20 pos [e]: (0 + 0, 0 + 0)
18:18:20 pos [ ]: (0 + 0, 0 + 0)
18:18:20 pos [r]: (0 + 0, 0 + 0)
18:18:20 pos [i]: (0 + 0, 0 + 0)
18:18:20 pos [g]: (0 + 0, 0 + 0)
18:18:20 pos [h]: (0 + 0, 0 + 0)
18:18:20 pos [t]: (0 + 0, 0 + 0)
18:18:20 pos [-]: (0 + 0, 0 + 0)
18:18:20 pos [c]: (0 + 0, 0 + 0)
18:18:20 pos [l]: (0 + 0, 0 + 0)
18:18:20 pos [i]: (0 + 0, 0 + 0)
18:18:20 pos [c]: (0 + 0, 0 + 0)
18:18:21 pos [k]: (0 + 0, 0 + 0)
18:18:21 pos [ ]: (0 + 0, 0 + 0)
18:18:21 pos [s]: (0 + 0, 0 + 0)
18:18:21 pos [u]: (0 + 0, 0 + 0)
18:18:21 pos [b]: (0 + 0, 0 + 0)
18:18:21 pos [r]: (0 + 0, 0 + 0)
18:18:21 pos [o]: (0 + 0, 0 + 0)
18:18:21 pos [u]: (0 + 0, 0 + 0)
18:18:21 pos [t]: (0 + 0, 0 + 0)
18:18:21 pos [i]: (0 + 0, 0 + 0)
18:18:21 pos [n]: (0 + 0, 0 + 0)
18:18:21 pos [e]: (0 + 0, 0 + 0)
18:18:21 pos [.]: (0 + 0, 0 + 0)
18:18:21 pos [ ]: (0 + 0, 0 + 0)
18:18:22 call modules handler : onWindowLeftClick
18:18:22 signal: left_click
18:18:22 ModRightClickTestEn.gs : @return
18:18:22 call modules handler : onConductorReturn
18:18:22 pos [b]: (0 + 0, 0 + 0)
18:18:22 pos [r]: (0 + 0, 0 + 0)
18:18:22 pos [o]: (0 + 0, 0 + 0)
18:18:22 pos [u]: (0 + 0, 0 + 0)
18:18:22 pos [t]: (0 + 0, 0 + 0)
18:18:22 pos [i]: (0 + 0, 0 + 0)
18:18:22 pos [n]: (0 + 0, 0 + 0)
18:18:22 pos [e]: (0 + 0, 0 + 0)
18:18:22 pos [.]: (0 + 0, 0 + 0)
18:18:22 pos [ ]: (0 + 0, 0 + 0)
18:18:22 pos [T]: (0 + 0, 0 + 0)
18:18:22 pos [h]: (0 + 0, 0 + 0)
18:18:22 pos [i]: (0 + 0, 0 + 0)
18:18:22 pos [s]: (0 + 0, 0 + 0)
18:18:22 pos [ ]: (0 + 0, 0 + 0)
18:18:22 pos [o]: (0 + 0, 0 + 0)
18:18:22 pos [ ]: (0 + 0, 0 + 0)
18:18:22 pos [t]: (0 + 0, 0 + 0)
18:18:22 pos [s]: (0 + 0, 0 + 0)
18:18:22 pos [u]: (0 + 0, 0 + 0)
18:18:22 pos [s]: (0 + 0, 0 + 0)
18:18:22 pos [ ]: (0 + 0, 0 + 0)
18:18:22 pos [ ]: (0 + 0, 0 + 0)
18:18:22 pos [f]: (0 + 0, 0 + 0)
18:18:22 pos [e]: (0 + 0, 0 + 0)
18:18:22 pos [t]: (0 + 0, 0 + 0)
18:18:22 pos [ ]: (0 + 0, 0 + 0)
18:18:22 pos [a]: (0 + 0, 0 + 0)
18:18:22 pos [ ]: (0 + 0, 0 + 0)
18:18:22 pos [s]: (0 + 0, 0 + 0)
18:18:22 pos [i]: (0 + 0, 0 + 0)
18:18:22 pos [ ]: (0 + 0, 0 + 0)
18:18:22 pos [s]: (0 + 0, 0 + 0)
18:18:22 pos [k]: (0 + 0, 0 + 0)
18:18:22 pos [c]: (0 + 0, 0 + 0)
18:18:22 pos [i]: (0 + 0, 0 + 0)
18:18:22 pos [l]: (0 + 0, 0 + 0)
18:18:22 pos [c]: (0 + 0, 0 + 0)
18:18:22 pos [ ]: (0 + 0, 0 + 0)
18:18:22 pos [t]: (0 + 0, 0 + 0)
18:18:22 pos [h]: (0 + 0, 0 + 0)
18:18:22 pos [g]: (0 + 0, 0 + 0)
18:18:22 pos [i]: (0 + 0, 0 + 0)
18:18:22 pos [r]: (0 + 0, 0 + 0)
18:18:22 pos [ ]: (0 + 0, 0 + 0)
18:18:22 pos [e]: (0 + 0, 0 + 0)
18:18:22 pos [h]: (0 + 0, 0 + 0)
18:18:22 pos [t]: (0 + 0, 0 + 0)
18:18:22 pos [T]: (0 + 0, 0 + 0)
18:18:22 pos [h]: (0 + 0, 0 + 0)
18:18:22 pos [i]: (0 + 0, 0 + 0)
18:18:22 pos [i]: (0 + 0, 0 + 0)
18:18:22 pos [s]: (0 + 0, 0 + 0)
18:18:22 pos [ ]: (0 + 0, 0 + 0)
18:18:22 pos [i]: (0 + 0, 0 + 0)
18:18:22 pos [n]: (0 + 0, 0 + 0)
18:18:22 pos [s]: (0 + 0, 0 + 0)
18:18:22 pos [i]: (0 + 0, 0 + 0)
18:18:22 pos [d]: (0 + 0, 0 + 0)
18:18:22 pos [e]: (0 + 0, 0 + 0)
18:18:22 pos [ ]: (0 + 0, 0 + 0)
18:18:22 pos [t]: (0 + 0, 0 + 0)
18:18:22 pos [h]: (0 + 0, 0 + 0)
18:18:22 pos [e]: (0 + 0, 0 + 0)
18:18:22 pos [ ]: (0 + 0, 0 + 0)
18:18:22 pos [r]: (0 + 0, 0 + 0)
18:18:22 pos [i]: (0 + 0, 0 + 0)
18:18:22 pos [g]: (0 + 0, 0 + 0)
18:18:22 pos [h]: (0 + 0, 0 + 0)
18:18:22 pos [t]: (0 + 0, 0 + 0)
18:18:22 pos [-]: (0 + 0, 0 + 0)
18:18:22 pos [c]: (0 + 0, 0 + 0)
18:18:22 pos [l]: (0 + 0, 0 + 0)
18:18:22 pos [i]: (0 + 0, 0 + 0)
18:18:22 pos [c]: (0 + 0, 0 + 0)
18:18:22 pos [k]: (0 + 0, 0 + 0)
18:18:22 pos [ ]: (0 + 0, 0 + 0)
18:18:22 pos [s]: (0 + 0, 0 + 0)
18:18:22 pos [u]: (0 + 0, 0 + 0)
18:18:22 pos [b]: (0 + 0, 0 + 0)
18:18:22 pos [r]: (0 + 0, 0 + 0)
18:18:22 pos [o]: (0 + 0, 0 + 0)
18:18:22 pos [u]: (0 + 0, 0 + 0)
18:18:22 pos [t]: (0 + 0, 0 + 0)
18:18:22 pos [i]: (0 + 0, 0 + 0)
18:18:22 pos [n]: (0 + 0, 0 + 0)
18:18:22 pos [e]: (0 + 0, 0 + 0)
18:18:22 pos [.]: (0 + 0, 0 + 0)
18:18:22 pos [ ]: (0 + 0, 0 + 0)
18:18:22 ModRightClickTestEn.gs :
18:18:22 ModRightClickTestEn.gs : @jump target=*next
18:18:22 call modules handler : onConductorJump
18:18:22 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
18:18:22 ModRightClickTestEn.gs : jumped to : *next
18:18:22 call modules handler : onBeforeConductorLabel
18:18:22 onLabelStore(*next, , 1) processed in 3 ms.
18:18:22 call modules handler : onConductorLabel
18:18:22 ModRightClickTestEn.gs : The test is over. [p][cm]
18:18:22 pos [T]: (0 + 0, 0 + 0)
18:18:22 pos [h]: (0 + 0, 0 + 0)
18:18:22 pos [e]: (0 + 0, 0 + 0)
18:18:22 pos [ ]: (0 + 0, 0 + 0)
18:18:22 pos [t]: (0 + 0, 0 + 0)
18:18:22 pos [e]: (0 + 0, 0 + 0)
18:18:22 pos [s]: (0 + 0, 0 + 0)
18:18:22 pos [t]: (0 + 0, 0 + 0)
18:18:22 pos [ ]: (0 + 0, 0 + 0)
18:18:22 pos [i]: (0 + 0, 0 + 0)
18:18:22 pos [s]: (0 + 0, 0 + 0)
18:18:22 pos [ ]: (0 + 0, 0 + 0)
18:18:22 pos [o]: (0 + 0, 0 + 0)
18:18:22 pos [v]: (0 + 0, 0 + 0)
18:18:22 pos [e]: (0 + 0, 0 + 0)
18:18:22 pos [r]: (0 + 0, 0 + 0)
18:18:22 pos [.]: (0 + 0, 0 + 0)
18:18:22 pos [ ]: (0 + 0, 0 + 0)
18:18:23 call modules handler : onWindowLeftClick
18:18:23 signal: left_click
18:18:23 pos [ ]: (0 + 0, 0 + 0)
18:18:23 pos [.]: (0 + 0, 0 + 0)
18:18:23 pos [r]: (0 + 0, 0 + 0)
18:18:23 pos [e]: (0 + 0, 0 + 0)
18:18:23 pos [v]: (0 + 0, 0 + 0)
18:18:23 pos [o]: (0 + 0, 0 + 0)
18:18:23 pos [ ]: (0 + 0, 0 + 0)
18:18:23 pos [s]: (0 + 0, 0 + 0)
18:18:23 pos [i]: (0 + 0, 0 + 0)
18:18:23 pos [ ]: (0 + 0, 0 + 0)
18:18:23 pos [t]: (0 + 0, 0 + 0)
18:18:23 pos [s]: (0 + 0, 0 + 0)
18:18:23 pos [e]: (0 + 0, 0 + 0)
18:18:23 pos [t]: (0 + 0, 0 + 0)
18:18:23 pos [ ]: (0 + 0, 0 + 0)
18:18:23 pos [e]: (0 + 0, 0 + 0)
18:18:23 pos [h]: (0 + 0, 0 + 0)
18:18:23 pos [T]: (0 + 0, 0 + 0)
18:18:23 ModRightClickTestEn.gs :
18:18:23 ModRightClickTestEn.gs : @rclick !call !jump
18:18:23 ModRightClickTestEn.gs : @hide_message layer=message0
18:18:23 call modules handler : onHideMessageLayer
18:18:23 ModRightClickTestEn.gs : @wait_hide_message
18:18:23 signal: message0_hide_completed
18:18:23 ModRightClickTestEn.gs :
18:18:23 ModRightClickTestEn.gs :
18:18:23 call modules handler : onConductorScenarioLoad

Issue has been fixed now.

**Comment by Halo1234** [comment]
Thank you for confirming. Can I merge them?

**Comment by a-rabin** [comment]
Of course.
I might do some pull requests soon to fix some sentences in the demo. But functionally, all seems to be OK.

**Pull request merged**
