### PR TITLE
Document is being translated into English.

### PR DESCRIPTION
**Pull request by Halo1234**
Document is being translated into English.

### CODE REVIEW

**Comment by a-rabin** [comment]
Excellent. Just a few errors on the Introduction page. I'm providing corrections in a few hours. Thank you!

**Comment by Halo1234** [comment]
Thank you for your review. I don't think I'll be able to do much work today, so I'll take it easy.

**Review by a-rabin — CHANGES_REQUESTED** [review]
Is this corrected paragraph about usage of ! in tags on introduction page good?

> Additionally, it is possible to extend tags by adding an exclamation mark (!) to ordinary tags. When specifying with @!make_character image=standing_character->true, no_character->false, it will be interpreted as @make_character standing_character, and if specified as @make_character image=true, it will be considered the same.

 > Furthermore, by adding a slash (/) to attributes, you can specify patterns. For example, specifying @!Hello /storage=A_<POSE>_<FACE> will replace the values with those specified in the pose and face attributes.

> In other words, if you specify @Hello pose=pose1 face=face1, it is equivalent to specifying @Hello storage=A_pose1_face1.

> These can also be used in combination. For instance, by using @!Hello /storage=A_<POSE>_<FACE> pose=pose1 face=face1, @Hello pose1 face1 will be converted to @Hello storage=A_pose1_face1.

**Comment by Halo1234** [comment]
thank you. I tried to fix it, but what do you think?

**Comment by a-rabin** [comment]
Thank you.
The following headings have corrupted viewing in English due to different text encoding.

1. ModADV page: set_timezone(make_time_zone�Ŏw�肵�����O)
2. ModADVBookmarks page: heading, load_system_variables

And some table data on Default tag page are untranslated.

**Comment by Halo1234** [comment]
thank you. I have corrected the issue.

**Comment by a-rabin** [comment]
Thank you very much. Seems to be alright now.

**Pull request merged**
